name: example
description: my_custom_data_table example

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  my_custom_data_table:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
